from toontown.toonbase.ToontownGlobals import *
wainscottingBase = [Vec4(0.8, 0.5, 0.3, 1.0), Vec4(0.699, 0.586, 0.473, 1.0), Vec4(0.473, 0.699, 0.488, 1.0)]
wallpaperBase = [Vec4(1.0, 1.0, 0.7, 1.0),
 Vec4(0.8, 1.0, 0.7, 1.0),
 Vec4(0.4, 0.5, 0.4, 1.0),
 Vec4(0.5, 0.7, 0.6, 1.0)]
wallpaperBorderBase = [Vec4(1.0, 1.0, 0.7, 1.0),
 Vec4(0.8, 1.0, 0.7, 1.0),
 Vec4(0.4, 0.5, 0.4, 1.0),
 Vec4(0.5, 0.7, 0.6, 1.0)]
doorBase = [Vec4(1.0, 1.0, 0.7, 1.0)]
floorBase = [Vec4(0.746, 1.0, 0.477, 1.0), Vec4(1.0, 0.684, 0.477, 1.0)]
baseScheme = {'TI_wainscotting': wainscottingBase,
 'TI_wallpaper': wallpaperBase,
 'TI_wallpaper_border': wallpaperBorderBase,
 'TI_door': doorBase,
 'TI_floor': floorBase}
colors = {DonaldsDock: {'TI_wainscotting': wainscottingBase,
               'TI_wallpaper': wallpaperBase,
               'TI_wallpaper_border': wallpaperBorderBase,
               'TI_door': doorBase,
               'TI_floor': floorBase},
 ToontownCentral: {'TI_wainscotting': wainscottingBase,
                   'TI_wallpaper': wallpaperBase,
                   'TI_wallpaper_border': wallpaperBorderBase,
                   'TI_door': doorBase + [Vec4(0.8, 0.5, 0.3, 1.0)],
                   'TI_floor': floorBase},
 TheBrrrgh: baseScheme,
 MinniesMelodyland: baseScheme,
 DaisyGardens: baseScheme,
 GoofySpeedway: baseScheme,
 DonaldsDreamland: {'TI_wainscotting': wainscottingBase,
                    'TI_wallpaper': wallpaperBase,
                    'TI_wallpaper_border': wallpaperBorderBase,
                    'TI_door': doorBase,
                    'TI_floor': floorBase},
 Tutorial: {'TI_wainscotting': wainscottingBase,
            'TI_wallpaper': wallpaperBase,
            'TI_wallpaper_border': wallpaperBorderBase,
            'TI_door': doorBase + [Vec4(0.8, 0.5, 0.3, 1.0)],
            'TI_floor': floorBase},
 MyEstate: baseScheme}

gagShopColors = {
  TheBrrrgh: {'TI_wainscotting': Vec4(0, 0.675, 0.84, 1),
              'TI_wallpaper': Vec4(0.64, 0.8, 0.92, 1),
              'TI_wallpaper_border': Vec4(0.64, 0.8, 0.92, 1),
              'TI_door': doorBase,
              'TI_floor': floorBase},
  DonaldsDreamland: {'TI_wainscotting': Vec4(0.51, 0.36, 0.63, 1),
              'TI_wallpaper': Vec4(0.35, 0.27, 0.42, 1),
              'TI_wallpaper_border': Vec4(0.35, 0.27, 0.42, 1),
              'TI_door': doorBase,
              'TI_floor': floorBase},
  MinniesMelodyland: {'TI_wainscotting': Vec4(0.67, 0.34, 0.63, 1),
              'TI_wallpaper': Vec4(0.93, 0.694, 0.88, 1),
              'TI_wallpaper_border': Vec4(0.93, 0.694, 0.88, 1),
              'TI_door': doorBase,
              'TI_floor': floorBase},
  DonaldsDock: {'TI_wainscotting': Vec4(0.8, 0.5, 0.3, 1),
              'TI_wallpaper': Vec4(0.92, 0.6, 0.43, 1),
              'TI_wallpaper_border': Vec4(0.92, 0.6, 0.43, 1),
              'TI_door': doorBase,
              'TI_floor': floorBase},
  DaisyGardens: {'TI_wainscotting': Vec4(0, 0.694, 0.415, 1),
              'TI_wallpaper': Vec4(0.7, 1, 0.7, 1),
              'TI_wallpaper_border': Vec4(0.7, 1, 0.7, 1),
              'TI_door': doorBase,
              'TI_floor': floorBase},            
 }