ACCESS_USER = 0
ACCESS_COMMUNITY = 1
ACCESS_CREATIVE = 100
ACCESS_MOD = 200
ACCESS_DEV = 300
ACCESS_ADMIN = 400
ACCESS_SYSTEM = 500

MIN_MAGIC_WORD_ACCESS = ACCESS_COMMUNITY

TARGET_SELF = 0
TARGET_OTHER = 1
TARGET_BOTH = 2